
# <p style="text-align: center;">MIS382: Advanced Predictive Modeling</p>
# <p style="text-align: center;">Assignment 5</p>
## <p style="text-align: center;">Total points: 35</p>
## <p style="text-align: center;">Due: Monday, November 27th, submitted via Canvas by 11:59 pm</p>

Your homework should be written in a **Jupyter notebook**. You may work in groups of two if you wish. Only one student per team needs to submit the assignment on Canvas.  But be sure to include name and UTID for both students.  Homework groups will be created and managed through Canvas, so please do not arbitrarily change your homework group.  

Also, please make sure your code runs and the graphics (and anything else) are displayed in your notebook before submitting. (%matplotlib inline)

# Question 1: Ensembles (1+12+2 = 15pts)
In this question, we will compare performance of different ensemble methods: [Random Forest](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html), [Gradient Boosting Decision Tree](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html) (GBDT), and [XGBoost](http://xgboost.readthedocs.io/en/latest/).  Note that you have to install xgboost package in addition to scikit-learn.  You can see installation guides [here](http://xgboost.readthedocs.io/en/latest/build.html).




Two  datasets are provided for this problem. For **each of the datasets ((X1.csv, y1.csv), (X2.csv, y2.csv))**, do the following:

1. Load the data and partition it into features (X) and the target label (y) for classification task. Then, use [train_test_split](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) to split data into training and testing: test_size=0.33, random_state=42.

2. Build a classifier using [Random Forest](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html), [Gradient Boosting Decision Tree](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html), and [XGBoost](http://xgboost.readthedocs.io/en/latest/), respectively, and answer the following for each classifier.

 - Mention any design choices (with reasoning/justification) that you made, e.g. the hyperparameters considered for each classifier.
 - Report the mean error rate (fraction of incorrect labels) and the confusion matrix on test data. <br>
 - Report the feature importance and time of execution (training and predicting times).

3. Compare the three classifiers for the two different datasets ((X1.csv, y1.csv), (X2.csv, y2.csv)) in terms of the misclassification rate.  What are the characteristics of the dataset and the classifiers that resulted in somewhat different comparative results?

In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
# from xgboost.sklearn import XGBClassifier
from time import time
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline

## Part 1

In [3]:
x1 = pd.read_csv('X1.csv', header = None)
x2 = pd.read_csv('X2.csv', header = None)

y1 = pd.read_csv('y1.csv', header = None)
y1 = y1[0].values
y2 = pd.read_csv('y2.csv', header = None)
y2 = y2[0].values

x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, 
                                                    test_size=0.33, 
                                                    random_state=42)

x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, 
                                                    test_size=0.33, 
                                                    random_state=42)

## Part 2

### Random Forest

#### X1 and Y1

In [45]:
RFC = RandomForestClassifier()
param_grid_RFC = { 'n_estimators' : [5,25,50],
                  'criterion' : ['gini', 'entropy']}
cv_RFC = GridSearchCV(estimator = RFC, param_grid=param_grid_RFC, cv=5)
cv_RFC.fit(x1_train, y1_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [5, 25, 50], 'criterion': ['gini', 'entropy']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [46]:
print 'Best Parameters: {}'.format(cv_RFC.best_params_)
print 'Best Score: {}'.format(cv_RFC.best_score_)

Best Parameters: {'n_estimators': 25, 'criterion': 'gini'}
Best Score: 0.873731343284


In [65]:
t0 = time()
best_RFC = RandomForestClassifier(n_estimators = 25, criterion = 'gini')
model_RFC = best_RFC.fit(x1_train, y1_train)
print "Fitting time: {} sec".format(round(time() - t0,3))

t1 = time()
y1_pred_RFC = model_RFC.predict(x1_test)
print 'Prediction time: {} sec'.format(round(time() - t1,3))

Fitting time: 0.784 sec
Prediction time: 0.021 sec


In [58]:
print confusion_matrix(y1_test, y1_pred_RFC)
print 'Percent Incorrect: {}%'.format(float(250+153)*100/(1431+1466))

[[1431  250]
 [ 153 1466]]
Percent Incorrect: 13.9109423542%


#### X2 and Y2

In [49]:
RFC = RandomForestClassifier()
param_grid_RFC = { 'n_estimators' : [5,25,50],
                  'criterion' : ['gini', 'entropy']}
cv_RFC = GridSearchCV(estimator = RFC, param_grid=param_grid_RFC, cv=5)
cv_RFC.fit(x2_train, y2_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [5, 25, 50], 'criterion': ['gini', 'entropy']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [50]:
print 'Best Parameters: {}'.format(cv_RFC.best_params_)
print 'Best Score: {}'.format(cv_RFC.best_score_)

Best Parameters: {'n_estimators': 50, 'criterion': 'gini'}
Best Score: 0.928955223881


In [66]:
t0 = time()
best_RFC = RandomForestClassifier(n_estimators = 50, criterion = 'gini')
model_RFC = best_RFC.fit(x2_train, y2_train)
print "Fitting time: {} sec".format(round(time() - t0,3))

t1 = time()
y2_pred_RFC = model_RFC.predict(x2_test)
print 'Prediction time: {} sec'.format(round(time() - t1,3))

Fitting time: 0.519 sec
Prediction time: 0.031 sec


In [59]:
print confusion_matrix(y2_test, y2_pred_RFC)
print 'Percent Incorrect: {}%'.format(float(73+45)*100/(777+755))

[[777  73]
 [ 45 755]]
Percent Incorrect: 7.70234986945%


### GBDT

#### X1 and Y1

In [17]:
GBC = GradientBoostingClassifier()
param_grid_GBC = {'learning_rate' : [.01, .1, 1],
              'max_depth' : [1,3,5]}
cv_GBC = GridSearchCV(estimator = GBC, param_grid=param_grid_GBC, cv=5)
cv_GBC.fit(x1_train, y1_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'learning_rate': [0.01, 0.1, 1], 'max_depth': [1, 3, 5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [18]:
print 'Best Parameters: {}'.format(cv_GBC.best_params_)
print 'Best Score: {}'.format(cv_GBC.best_score_)

Best Parameters: {'learning_rate': 0.1, 'max_depth': 5}
Best Score: 0.910447761194


In [67]:
t0 = time()
best_GBC = GradientBoostingClassifier(learning_rate = .01,
                                     max_depth = 5)
model_GBC = best_GBC.fit(x1_train, y1_train)
print "Fitting time: {} sec".format(round(time() - t0,3))

t1 = time()
y1_pred_GBC = model_GBC.predict(x1_test)
print 'Prediction time: {} sec'.format(round(time() - t1,3))

Fitting time: 3.26 sec
Prediction time: 0.009 sec


In [21]:
print confusion_matrix(y1_test, y1_pred_GBC)
print 'Percent Incorrect: {}%'.format(float(230+160)*100/(1451+1459))

[[1451  230]
 [ 160 1459]]
Percent Incorrect: 13.4020618557%


#### X2 and Y2

In [22]:
GBC = GradientBoostingClassifier()
param_grid_GBC = {'learning_rate' : [.01, .1, 1],
              'max_depth' : [1,3,5]}
cv_GBC = GridSearchCV(estimator = GBC, param_grid=param_grid_GBC, cv=5)
cv_GBC.fit(x2_train, y2_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'learning_rate': [0.01, 0.1, 1], 'max_depth': [1, 3, 5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [23]:
print 'Best Parameters: {}'.format(cv_GBC.best_params_)
print 'Best Score: {}'.format(cv_GBC.best_score_)

Best Parameters: {'learning_rate': 0.1, 'max_depth': 5}
Best Score: 0.928358208955


In [68]:
t0 = time()
best_GBC = GradientBoostingClassifier(learning_rate = .01,
                                     max_depth = 5)
model_GBC = best_GBC.fit(x2_train, y2_train)
print "Fitting time: {} sec".format(round(time() - t0,3))

t1 = time()
y2_pred_GBC = model_GBC.predict(x2_test)
print 'Prediction time: {} sec'.format(round(time() - t1,3))

Fitting time: 1.179 sec
Prediction time: 0.005 sec


In [26]:
print confusion_matrix(y2_test, y2_pred_GBC)
print 'Percent Incorrect: {}%'.format(float(119+83)*100/(731+717))

[[731 119]
 [ 83 717]]
Percent Incorrect: 13.9502762431%


### XG Boost

# Question 2: Visualization using Bokeh (10 pts)

In this problem, you'll build an interactive visualization. Bokeh is a Python interactive visualization library that targets modern web browsers for presentation. For more information on Bokeh, see http://bokeh.pydata.org/en/latest/. The problem statement is as follows:

Using the "nbasalariesfull.csv" data set from HMK4, your goal is to build a Bokeh visualization which allows the user to explore how salary (on a log scale) varies with points per game (PSG) and age. You will create a visualization that allows the user to toggle the X axis of a scatter plot between PSG and age, with the y-axis always being log Salary. Also add the hover tool so that if the user hovers over a datapoint in the plot a window pops up that shows the player name, team, position, salary, and the current x variable (PSG or age) depending on the current tab.  Color each point according to a player's position and provide a legend for the colors. Add the ability to Zoom in/out.  Add slight horizontal jitter to a player's age.

Hints: 
1. see: http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#basic-tooltips for hover and zoom tool examples.
2. See: http://bokeh.pydata.org/en/latest/docs/reference/plotting.html. Look for the scatter API.
3. See: http://bokeh.pydata.org/en/0.10.0/docs/user_guide/styling.html#labels. For labeling axes.
4. See: https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html  for how to use jitter transform
5. See: http://bokeh.pydata.org/en/latest/docs/gallery/iris.html for coloring points by category
6. Use output_notebook() from Bokeh to output the plot to your notebook

Include an image screenshot in addition to the visualization output.

In [11]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
from bokeh.models.widgets import Panel, Tabs
from bokeh.models import CustomJS, ColumnDataSource, HoverTool, BoxZoomTool
from bokeh.transform import jitter
from bokeh.plotting import figure, output_notebook, show

data = pd.read_csv("nbasalariesfull.csv")
data["logsalary"] = data.SALARY.apply(np.log)

## Solution

# Question 3: Diabetes classification using support vector machines (4+3+3=10 pts) 
(a) Apply a linear SVM, using the scikit-SVM, for the Pima Indian Women diabetes detection problem on the dataset provided (details on dataset here  http://archive.ics.uci.edu/ml/datasets/Pima+Indians+Diabetes) . Specify how you chose the slack cost/penalty (‘C’ parameter)for the model. Maintain all other parameters as default. Hint: http://scikit-learn.org/stable/modules/generated/sklearn.grid_search.GridSearchCV.html will make 10-fold cross-validation easier.
The code to get the training/testing data is provided below.

(b) Repeat (a) but using a Gaussian radial basis kernel.

(c) Summarize the comparative performance (mean error rates) of the classifiers. What do you conclude? (be brief).

In [18]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn import grid_search

data_train = pd.read_csv('diabetes_train-log.csv')
data_test = pd.read_csv('diabetes_test-log.csv')
cols = ['numpreg', 'plasmacon', 'bloodpress', 'skinfold', 'seruminsulin', 'BMI', 'pedigreefunction', 'age']

xtrain = np.asmatrix(data_train[cols])
ytrain = np.asarray(data_train['classvariable']).T

xtest = np.asmatrix(data_test[cols])
ytest = np.asarray(data_test['classvariable']).T

## SOLUTION